version: "3.7"

services:
  redirecterr:
    tty: true
    image: aldmbmtl/redirecterr
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - ./src:/app
      - ./config.yaml:/config.yaml
